### ISSUE TITLE
Configure Dependabot for GitHub Actions

### ISSUE THREAD

**Issue by ccjernigan** [zodl-inc/zodl-ios#700]
## Is your feature request related to a problem? Please describe.
We don't have a reliable way to detect when GitHub Actions have new versions

## Describe the solution you'd like
Configure `.github/dependabot.yml` file with the following
```
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
```

You can see an example in context here: https://github.com/zcash/secant-android-wallet/blob/main/.github/dependabot.yml
